### ISSUE TITLE
是否支持session共享呢

### ISSUE THREAD

**Issue by Mr-Zhe** [wuyouzhuguli/FEBS-Security#14]
如果使用多台机器部署怎么实现session共享呢

**Comment by wuyouzhuguli** [comment]
session存redis里了，所以多台实例指向同一个redis地址或者redis集群即可。

**Comment by Mr-Zhe** [comment]
麻烦请教一下代码在哪里呢，只要配置了这两个地方就可以了吗
=======================================
# session 存储到 redis，实现分布式 session
  session:
    store-type: redis
    redis:
      namespace: febs:spring:session
=======================================
.sessionManagement() // 配置 session管理器
                .invalidSessionStrategy(invalidSessionStrategy()) // 处理 session失效
                .maximumSessions(febsSecurityProperties.getSession().getMaximumSessions()) // 最大并发登录数量
                .expiredSessionStrategy(new FebsExpiredSessionStrategy()) // 处理并发登录被踢出
                .sessionRegistry(sessionRegistry()) // 配置 session注册中心

**Comment by wuyouzhuguli** [comment]
yml里redis的连接配置一样就可以了

**Comment by Mr-Zhe** [comment]
除了配置Redis以外，还需要操作什么不，比如说启用某个注解，我想看看session共享到Redis到底是怎么生效的

**Comment by wuyouzhuguli** [comment]
yml配置：
```yml
session:
  store-type: redis
```
就是将session保存到redis，没有别的配置或注解了

**Comment by Mr-Zhe** [comment]
好的，谢谢了哈
