### ISSUE TITLE
Failed to run FebsApplication. said "org.apache.commons.io does not exist"

### ISSUE THREAD

**Issue by XFJH** [wuyouzhuguli/FEBS-Security#18]
Thanks your share this project, it help me a lot! I am new bee in java dev,

I noticed from last commit, this project can't build right, below is the detial info:

commit 0a9150a418be718853b7d54a641d795baa492935 (HEAD -> master, origin/master, origin/HEAD)
Author: mrbird <852252810@qq.com>
Date:   Mon Jun 17 19:18:35 2019 +0800

    修复流未关闭

------------------------------------------------------------------------
From recent commited  on "cc/mrbird/common/utils/AddressUtils.java" file
new added before line: 
`import org.apache.commons.io.FileUtils;`

When I started fesb web application , on building , I get follow question: 
"Error:(3, 29) java: package org.apache.commons.io does not exist"

is there any dependency pom need to be added to pom.xml?

**Comment by wuyouzhuguli** [comment]
sorry,I forget to add this[https://github.com/wuyouzhuguli/FEBS-Security/commit/ba02532ba97761353b15884e3d0fccabb4d9c146](https://github.com/wuyouzhuguli/FEBS-Security/commit/ba02532ba97761353b15884e3d0fccabb4d9c146):
```xml
<dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.6</version>
</dependency>
```
